version: '3'
services:
  server:
    build: 
      context: ./server
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/parenting-diary
      - JWT_SECRET=your_secret_key
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
    depends_on:
      - mongo

  client:
    build: 
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  mongo:
    image: mongo
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 